Frontend: upgrade Vue and switch to Ethers
thousandetherhomepage/ketherhomepage pull request #51
Opened 2021-04-25 17:21 UTC by mveytsman

- Rebuilt the app on Nuxt
- Got ethers installed and working with static JsonRPC
- TODO
- [ ] Working in metamask
- [ ] Event subscriptions
- [ ] Buying ads using ethers `signer`
- [ ] Network switching when not in metamask
- [ ] Error handling for the Promise-based ethers api

Questions for @shazow 
- Ethers returns "homestead" as the mainnet network name instead of "main". Can this cause problems in the future if we hardcode this string?
- Did I understand your intentions here: https://github.com/thousandetherhomepage/ketherhomepage/compare/upgrade-vue?expand=1#diff-fa059326cb969bbb3af4440b534bbfb369e32c1b75513a56348dbe8b4b2522bfR33 (I know it's a very old TODO, just curious if you remember).
- Revisit the bugs we had with Web3's BigNumbers.

2021-04-25 17:29 UTC, shazow commented
1. I think homestead is fine: https://github.com/thousandetherhomepage/ketherhomepage/pull/50/files#diff-06c67406a4d044fe2c49714374e3dabd78d88ff60ec9a9aa11aecd483e7dcdabR15
2. Yea we should make a computed property that just returns renderable ads, so we don't generate DOM for invalid ads I guess? But also I don't think that's really possible. And we're gonna render empty ads as placeholder blocks later.
3. Let's switch to using ethers' bignumber implementation where possible. I migrated tests to that in #50.

2021-04-25 17:30 UTC, shazow requested changes
Wanna remove the duplicate stuff from src in this PR so we can see the deltas?

2021-04-25 17:51 UTC, shazow reviewed
Some code in here looks useful too: https://github.com/bmiller59/vue-cli-plugin-ethers/blob/master/generator/templates/module/ethersConnect.js

2021-04-25 17:51 UTC, shazow commented on components/App.vue
> +    //TODO this was called "main" in web3, but ethers calls mainnet "homestead". Will using the name homestead break during some furture eth upgrade?
Yea, change it to `homestead`, but maybe keep an alias with `main` just in case.

2021-05-16 18:51 UTC, mveytsman commented
@shazow I thought I dropped my TODO in here since we last paired but I guess I have not:

Here's my todo from May 11th, updated for today

- [x] unsuported network in the bottom menu
- [x] error about provider
- [x] clicking buy triggers a vuex error. Instead it should prompt you to choose a wallet.
- [x] Migrate static footer links (FAQ, Press, )
- Metamask
	- [x] with metamask: handle ropsten and others
- [ ] Verify "show NSFW"
- [ ] Monitor events
- [x] Resize dragging things don't appear
- [ ] Make a purchase on Rinkeby in a non-symmmetric slot to make sure we didn't invert coordinates 
- [x] in metamask call it main not homestead

The main thing we need to do is get purchasing and events to work and actually test this. I think we will be able to deploy this after next pair.

2021-05-17 22:07 UTC, shazow commented
@mveytsman Pushed monitor events, but still need to be verified. Also fixed network switching in non-wallet.

2021-08-09 18:09 UTC, merged